server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: api-gateway
          uri: https://github.com/A-caro/proyect-Artistas.git
          search-paths: config-data
  application:
    name: config-service

